### ISSUE TITLE
initialisePortfolio() function results in error code 0

### ISSUE THREAD

**Issue by pavondunbar** [alex-straw/crypto-index-fund#1]
Hello there,

My name is Pavon Dunbar.  I am writing to you guys because first, I really like your Crypto Index Fund smart contracts.  I was able to successfully compile and deploy your contracts on the Ropsten testnet.  

During contract interaction, I was able to use the Factory contract to create the portfolio as specified in your instructions with no issues.  However, when I tried to access the **_initialisePortfolio()_** function, the result comes back with an error code 0.  

I even tried to pass the new Portfolio address as a parameter but with no success.

How can I use the initialisePortfolio() function after I create the portfolio in the Factory contract?

I am using truffle to compile and deploy and truffle console to interact with the newly deployed contracts.

Thanks in advance.

Pavon

**Comment by alex-straw** [comment]
Hi Pavon,

I'm really glad you like it!

After you've created the portfolio using the factory, you'll need to get the contract address for the newly created portfolio. If it's the first one you've created, then you can get it by indexing the array 'portfolios' (on the portfolioFactory.sol contract) with index [0]. Once you've got the address of the new portfolio you need to send some Ether to the initialise portfolio function for that particular contract address. You might struggle with a lot of these portfolios on test nets as they have limited liquidity on Uniswap.

Please let me know if that answers your question, but if you need more help then I'd be happy to call 🙂. My recommendation would be to just copy-paste the code for the factory and portfolio into Remix, and then you can easily retrieve the new contract address etc.

Just tried this myself to verify this makes sense (using Remix)

1) I deploy the PortfolioFactory.sol to '0x87C8f2cfE62AcC3438b4294A1608f3eeB51A8124' (on Kovan)
2) I call the Create function with a portfolio of 50% LINK and 50% WETH on Kovan:

"testPortfolio","TP",["0xa36085F69e2889c224210F603D836748e7dC0088","0xd0A1E359811322d97991E03f863a0C30C2cF029C"],[50,50],10

3) Then I call the portfolio array variable with index 0 to get the address of my newly created contract: '0x4ca63568Eae034693e7F9D2D1A5dFC3C219263Bc'

4) I use the 'At Address' with '0x4ca63568Eae034693e7F9D2D1A5dFC3C219263Bc' (to get access to that contract's functions)
5) I call the initialisePortfolio function with an arbitrary amount of WEI: 10000000 
6) Now my portfolio is set up and anyone can interact with it

**Comment by pavondunbar** [comment]
Thank you Alex!!

I appreciate your response.

I am good all the way to **Step 5 above**.  

How are you sending the Ether to the newly created Portfolio contract using the initialisePortfolio() function?  

I'm trying to send the ETH by doing this:

initialisePortfolio(2000000000000000000);

but the terminal is throwing an error saying **_Error: Invalid number of parameters for "initialisePortfolio". Got 1 expected 0!\n'_**

I guess I need to find out how to send money to the new Portfolio contract that I created in the factory.

I even did a manual send using Metamask to the newly created Portfolio contract address.  For some reason the initialisePortfolio function is the one giving me the errors.

Once I solve that, the other functions will work fine (buy, sell, redeem).

I'll try it in Remix too just to make sure.

Thank you in advance for all your help.  I truly appreciate it. 

Pavon

**Comment by alex-straw** [comment]
Hi Pavon,

I think it might be because the transaction to initialisePortfolio needs to have value:2000000000. I think that you might be passing it as an input argument to the function - and this function doesn't take any inputs, but it is payable. The functionality works using msg.value (i.e., the value you send) so without sending any value the function call will fail. Send me a link to your repo and I can give you a hand

**Comment by pavondunbar** [comment]
Good day Mr. Alex,

Once again, thank you for your time regarding this.  I sincerely appreciate it.

I've attached a screenshot of the error I am receiving **even though I am sending Ether to the initialisePortfolio() function**.

My newly deployed portfolio contract address (at _**portfolios(0)**_) is 0xb0E696883d3d9Aa806C7412D7310c85c41cCF299.

My deployed Portfolio contract address is 0xD6d5a3A30FBC9ecaFffac79b8C0Dc3E2D3b3A0A8

My deployed PortfolioFactory contract address is 0xe59850E124B39B478a5c79074C06789b5DED4036

I've even set the gas and gasPrice in addition to the value in the initialisePortfolio() function with no success.

I know I am missing something that is clear as day. And your responses have helped a lot so I really appreciate it.

Have a great weekend.  I'll figure this out somehow.

Pavon

<img width="1775" alt="Screenshot 2022-06-10 at 6 13 35 PM" src="https://user-images.githubusercontent.com/36899956/173162031-386637b2-8426-4965-b851-9957a9911e17.png">

**UPDATE:**  I just thought about something.  Would a possible reason my portfolio isn't being initialised is because I have 4 tokens in my portfolio and some of them may not be on Uniswap? In other words, do the tokens I create in the portfolio **_have to be tradable on Uniswap?_**

The 4 tokens in my portfolio are:

1. 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599 - Wrapped Bitcoin - 25%
2. 0x514910771AF9Ca656af840dff83E8264EcF986CA - ChainLink - 25%
3. 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984 - UniSwap - 25%
4. 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9 - Aave - 25%

Thanks!! :-)

**Comment by alex-straw** [comment]
Hi Pavon,

I suspect that it might a gas estimation error - more than likely because there isn't liquidity for UniSwap or Aave (maybe even WBTC) on Ropsten. If you try with just LINK and WETH do you have any luck?

edit:

So when the tokens are purchased they're just market bought from Uniswap - which comes with dangers without Oracles as you risk getting Sandwich attacked (which is why I wouldn't recommend deploying to mainnet) - which relies on actual liquidity in the pool for that pair. Also, BTC has decimals of 6 (IIRC) and ETH has 18, which means that our token allocation gets a bit weird unless you send more than like 1^12 WEI (although I haven't tested just yet). Hope this answers some of your questions. You can check if a pair has good liquidity by checking the Uniswap app and entering a trade from say WETH to AAVE (make sure you are on the test net version of Uniswap though). The most reliable ones on Kovan for me were LINK, DAI, and BAT.

**Comment by pavondunbar** [comment]
Good day, Mr. Alex:

You're right.  When I checked the Ropsten test network on the Uniswap liquidity pool page, most of the tokens had insufficient liquidity.

LINK wasn't even on the Uniswap Ropsten test network.

I'm trying to get some Kovan ETH to test on Kovan network. I'm sure now that my network is the issue and not the initialisePortfolio() function.

Thanks again for all your help!  Please feel free to close this ticket. 

If I encounter the same error after acquiring enough Kovan, I'll reopen a new one.

One more question before this ticket gets closed:

If there is a function to create portfolios in the Factory contract, why do parameters in the constructor of the Portfolio contract have to be passed before deployment?  And when we do pass these parameters, what happen to that portfolio that is created prior to deployment?  See screenshot of my deploy script for clarification:

<img width="798" alt="Screenshot 2022-06-13 at 1 35 02 PM" src="https://user-images.githubusercontent.com/36899956/173421687-92ef4111-ad22-4ca0-b672-0e612bb037c9.png">

You are the man!!  Thanks again.  I truly appreciate all your help with this!

Enjoy your day and your week, sir!

Pavon
